### ISSUE TITLE
csproj Errors

### ISSUE THREAD

**Issue by zortos293** [BetaWRLD/BetaManager#2]
2>C:\Users\Zortos\AppData\Local\Temp\tmpc5c5edac87e242a3bf0fbb7b681e8a37.proj(28,1): error MSB3202: The project file "C:\Users\Zortos\source\repos\BetaForkManager\BetaManager.csproj" was not found.
4>C:\Users\Zortos\AppData\Local\Temp\tmp1f1deeb5f4964939bf3b0e9d92e07b5f.proj(28,1): error MSB3202: The project file "C:\Users\Zortos\source\repos\BetaForkManager\BetaManager Updater\BetaManager Updater.csproj" was not found.
3>C:\Users\Zortos\AppData\Local\Temp\tmpe09b453140744cfd8f151adfc39e4afa.proj(28,1): error MSB3202: The project file "C:\Users\Zortos\source\repos\BetaForkManager\BetaManager-Uploader\BetaManager-Uploader.csproj" was not found.

**Comment by Kyrela** [comment]
I'm also interested in `BetaManager*.csproj` files so I can compile and test the project myself. Is there an ETA on when are we going to get these?
